<?php

/*
	This autoloader can be used when you cannot use Composer and/or its autogenerated autoloader.
	Use case #1: you put library to vendor/{vendorname}/{packagename}/ and call require_once({this_file_path});
	Use case #2: you put library to src/ directory and uncomment line with $irr_autoloader_library_mode = true; and define absolute path to src/ dir and call require_once({this_file_path});
*/

$irr_autoloader_library_mode = true;
$irr_autoloader_package_path = 'D:\\dev\\xampp\\htdocs\\science\\src';

spl_autoload_register(function($class) use ($irr_autoloader_library_mode, $irr_autoloader_package_path) {
	if (DIRECTORY_SEPARATOR!="\\") {
		$class = join(DIRECTORY_SEPARATOR, explode("\\", $class));
	}

	// strip 2 levels from path (vendor_name/library_name)
	$vendor_path = join(DIRECTORY_SEPARATOR, array_slice(explode(DIRECTORY_SEPARATOR, __DIR__), 0, -2));

	if (!empty($irr_autoloader_library_mode)) {
		$vendor_path = $irr_autoloader_package_path;
		$class = join(DIRECTORY_SEPARATOR, array_slice(explode(DIRECTORY_SEPARATOR, $class), 2));
	}

	$class = $vendor_path.DIRECTORY_SEPARATOR.$class.'.php';
	if (file_exists($class)) {
		require $class;
	}
});

?>