<?php
namespace irrevion\science\Physics\Unit\Entities;

class MmHg implements Pressure, NonStandard {
	const name = 'millimetre of mercury';
	const short_name = 'mmHg';
	// const category = 'pressure'; // defined by interface
	// const unit_system = 'NonStandard'; // defined by interface
	const measure = 'mmHg';
	const reference = 133.322387415;
	const reference_measure = 'Pa';
	const alias = 'P';
	const descr = 'A millimetre of mercury is a manometric unit of pressure, formerly defined as the extra pressure generated by a column of mercury one millimetre high, and currently defined as exactly 133.322387415 pascals or approximately 133.322 pascals. It is denoted mmHg or mm Hg.'; // https://en.wikipedia.org/wiki/Millimetre_of_mercury
	const base = 'M*L**-1*T**-2';
}
?>